### ISSUE TITLE
 YOU SUPPLIED TWO ATOMS 0.000000APART

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [tiwarylab/GrASP#11]
A structure crashed with this error: `ERROR: THIS CODE IS KNOWN TO FAIL WHEN ATOMS ARE VIRTUALLYON TOP OF ONE ANOTHER. YOU SUPPLIED TWO ATOMS 0.000000APART. QUITTING NOW.`

I think this is related to `mdtraj`: https://github.com/mdtraj/mdtraj/issues/1300.

I think `mdtraj` just clashes here: https://github.com/tiwarylab/GrASP/blob/75986d71441a589adbddffbf847ccc613eb89bbd/featurize_protein.py#L106
Even if I remove the `raise e` here: https://github.com/tiwarylab/GrASP/blob/75986d71441a589adbddffbf847ccc613eb89bbd/parse_files.py#L690

It still clashes.

**Comment by zwsmith200** [comment]
Is this related to the ongoing `altLoc` discussion? If so, I would like to condense that structure prep conversation into one thread.

**Comment by JavierSanchez-Utges** [comment]
It seems so. I ran `clean_pdb.py` on the 2307 structures of my dataset and only got one atom warning:
```
~/miniconda3/envs/ob/lib/python3.7/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: SE
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))}
```

This will only work for PDB format, but seems after being _cleaned_ with the script, atoms will be featurised without a problem.

You can now combine the three issues together if you want! Thanks!

**Comment by zwsmith200** [comment]
Great, the Se atoms shouldn't be a problem because we convert Selenomethionine to Methionine later.
