### ISSUE TITLE
Unit cell dimensions not found

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [tiwarylab/GrASP#12]
I have pre-processed my structures, to split into chains, and as a result some metadata are lost, such us the unit cell dimensions'. I get this warning from MDAnalysis:
```
~/miniconda3/envs/ob/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:747: UserWarning: Unit cell dimensions not found. CRYST1 record set to unitary values.
  warnings.warn("Unit cell dimensions not found. "
```

I think it is just to extract the coordinates, so it should not have any effect on the GrASP featurisation of the atoms, should it?

Thanks!

**Comment by zwsmith200** [comment]
This should be fine. This warning happens when `u.dimension == None` which means the distances in MDA will not consider periodic boundaries. I find it safer to remove these anyway because I've seen artifacts from it in the past.
