### ISSUE TITLE
environment installation fails

### ISSUE THREAD

**Issue by ashrayar** [tiwarylab/GrASP#14]
I am trying to install the two conda environments using the .yml files provided. But both the installation fails with different errors. The ob_env fails with some package incompatibility error and pytorch_env fails with a pip error. I have attached the screenshot for both. I am trying to install them in a Redhat linux system.

**ob_env error:**
<img width="1236" alt="Screen Shot 2024-04-23 at 6 10 45 PM" src="https://github.com/tiwarylab/GrASP/assets/38808825/a7a881cb-e811-41c8-baeb-f3367e2a59db">

**pytorch_env error:**

<img width="1072" alt="Screen Shot 2024-04-23 at 6 11 16 PM" src="https://github.com/tiwarylab/GrASP/assets/38808825/da241fdf-b818-4505-9b86-a8a680f87fb2">

**Comment by zwsmith200** [comment]
Thanks for the error reports. @Michael-C-Strobel is currently working on updating these for #7. I will close this issue so we can collect the installation issues in one location.
