### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by LenaParigger** [tiwarylab/GrASP#15]
Your tool seems very useful, nice work! Could you please add a license, e.g. MIT, to the git? Thank you so much!

**Comment by Michael-C-Strobel** [comment]
Thank you for pointing this out. I've added it in commit [b6f4b94](https://github.com/tiwarylab/GrASP/commit/b6f4b9489ad3b8d9a0e38abb7eb141ee35e4e5be).

**Comment by LenaParigger** [comment]
Many thanks! :)
