### ISSUE TITLE
CIF format

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [tiwarylab/GrASP#5]
Does GrASP work with mmCIF format?

**Comment by Michael-C-Strobel** [comment]
Thank you for your interest in GrASP! At this time mmCIF is not supported as it's not yet supported in MDAnalysis. There's an issue raised here: https://github.com/MDAnalysis/mdanalysis/issues/2367

Until then, you can use either PDB or mol2 formats. Other formats may be working but haven't been tested.
